### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by yourpalsonja** [Shopify/css#21]
Update the Mixins section!

### Todos:

- [ ] Create a `2020-update_mixins` branch

### Questions
- Is it worth it to combine functions and maps here, and title this section `SASS features`? [See a similar question here.](https://github.com/Shopify/css/issues/20)
- How is the colour system that's being rolled out going to affect this? @AndrewMusgrave @dleroux  we need your insight here!

**Comment by ananyaneogi** [comment]
> Is it worth it to combine functions and maps here, and title this section SASS features?

I think it is totally worth doing that. We can also clarify the difference between all these and write some guidelines on when to use what. 

Under `SASS features` we can have separate sections of -
- mixins
- functions
- maps
- any other sass features we use or want to use

Also IMO, properly sectioned documentation is always easy to consume, rather than one really long doc!
